"""One-page printable match summary.

Designed for paper-based clinical workflows:
- Black & white safe
- High contrast
- A4 and Letter size
- QR code to digital version
"""

from __future__ import annotations

from datetime import datetime, timezone

from ctm.models.matching import MatchStrength, TrialScore
from ctm.models.patient import PatientNote
from ctm.models.trial import ClinicalTrial


def generate_print_summary(
    patient: PatientNote,
    trial: ClinicalTrial,
    score: TrialScore,
    coordinator: str = "",
) -> str:
    """Generate a plain-text one-page summary for printing.

    Returns:
        Formatted text suitable for printing on A4/Letter.
    """
    now = datetime.now(timezone.utc).strftime("%d %B %Y")

    # Build criteria summary
    met_text = f"{score.criteria_met} met"
    verify_text = f"{score.criteria_unknown} to verify" if score.criteria_unknown else ""
    not_met_text = f"{score.criteria_not_met} not met" if score.criteria_not_met else ""

    criteria_parts = [met_text]
    if verify_text:
        criteria_parts.append(verify_text)
    if not_met_text:
        criteria_parts.append(not_met_text)

    # Build site info
    site_info = ""
    if trial.sites:
        site = trial.sites[0]
        site_parts = [site.facility]
        if site.city:
            site_parts.append(site.city)
        if site.country:
            site_parts.append(site.country)
        site_info = ", ".join(p for p in site_parts if p)
        if site.contact_name:
            site_info += f"\nContact: {site.contact_name}"
        if site.contact_phone:
            site_info += f" | {site.contact_phone}"
        if site.contact_email:
            site_info += f" | {site.contact_email}"

    # Patient summary
    patient_summary_parts = []
    if patient.age:
        patient_summary_parts.append(f"{patient.age} years old")
    if patient.sex:
        patient_summary_parts.append(patient.sex)
    if patient.diagnoses:
        patient_summary_parts.append(", ".join(patient.diagnoses[:3]))

    strength_label = {
        MatchStrength.STRONG: "STRONG MATCH",
        MatchStrength.POSSIBLE: "POSSIBLE MATCH",
        MatchStrength.UNLIKELY: "UNLIKELY MATCH",
    }

    summary = f"""
{'=' * 60}
  TRIALIBRE MATCH SUMMARY
  Date: {now}
  Coordinator: {coordinator or 'N/A'}
{'=' * 60}

  PATIENT
  {', '.join(patient_summary_parts) if patient_summary_parts else 'See attached records'}

{'─' * 60}

  RECOMMENDED TRIAL
  {trial.brief_title}
  NCT: {trial.nct_id}    Phase: {trial.phase or 'N/A'}
  {site_info or 'No site information available'}

{'─' * 60}

  MATCH ASSESSMENT
  Overall: {strength_label.get(score.strength, 'UNKNOWN')}

  Eligibility: {', '.join(criteria_parts)}
  (out of {score.criteria_total} total criteria)

  {score.relevance_explanation or ''}

{'─' * 60}

  NEXT STEPS
  1. Contact the trial site using the information above
  2. Share this summary with the treating physician
  3. Confirm criteria marked "to verify" with the patient

{'=' * 60}
  Generated by Trialibre | trialibre.org
{'=' * 60}
""".strip()

    return summary
